# Imports
from Characteristics import Characteristics_Dict
from Computer import Easy_Mode, Normal_Mode, Hard_Mode
from tkinter import *
from tkinter import ttk
from PIL import Image, ImageTk

# Create the game window
window = Tk()
window.title("Guess Who?")
window.state("zoomed")

# Characters directories 
Alex_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Alex.png')
Alex_Image = Alex_Image.resize((135, 320))
Alex_Image = ImageTk.PhotoImage(Alex_Image)
Alfred_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Alfred.png')
Alfred_Image = Alfred_Image.resize((135, 320))
Alfred_Image = ImageTk.PhotoImage(Alfred_Image)
Anita_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Anita.png')
Anita_Image = Anita_Image.resize((135, 320))
Anita_Image = ImageTk.PhotoImage(Anita_Image)
Anne_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Anne.png')
Anne_Image = Anne_Image.resize((135, 320))
Anne_Image = ImageTk.PhotoImage(Anne_Image)
Bernard_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Bernard.png')
Bernard_Image = Bernard_Image.resize((135, 320))
Bernard_Image = ImageTk.PhotoImage(Bernard_Image)
Bill_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Bill.png')
Bill_Image = Bill_Image.resize((135, 320))
Bill_Image = ImageTk.PhotoImage(Bill_Image)
Charles_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Charles.png')
Charles_Image = Charles_Image.resize((135, 320))
Charles_Image = ImageTk.PhotoImage(Charles_Image)
Claire_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Claire.png')
Claire_Image = Claire_Image.resize((135, 320))
Claire_Image = ImageTk.PhotoImage(Claire_Image)
David_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\David.png')
David_Image = David_Image.resize((135, 320))
David_Image = ImageTk.PhotoImage(David_Image)
Eric_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Eric.png')
Eric_Image = Eric_Image.resize((135, 320))
Eric_Image = ImageTk.PhotoImage(Eric_Image)
Frans_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Frans.png')
Frans_Image = Frans_Image.resize((135, 320))
Frans_Image = ImageTk.PhotoImage(Frans_Image)
George_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\George.png')
George_Image = George_Image.resize((135, 320))
George_Image = ImageTk.PhotoImage(George_Image)
Herman_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Herman.png')
Herman_Image = Herman_Image.resize((135, 320))
Herman_Image = ImageTk.PhotoImage(Herman_Image)
Joe_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Joe.png')
Joe_Image = Joe_Image.resize((135, 320))
Joe_Image = ImageTk.PhotoImage(Joe_Image)
Maria_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Maria.png')
Maria_Image = Maria_Image.resize((135, 320))
Maria_Image = ImageTk.PhotoImage(Maria_Image)
Max_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Max.png')
Max_Image = Max_Image.resize((135, 320))
Max_Image = ImageTk.PhotoImage(Max_Image)
Paul_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Paul.png')
Paul_Image = Paul_Image.resize((135, 320))
Paul_Image = ImageTk.PhotoImage(Paul_Image)
Peter_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Peter.png')
Peter_Image = Peter_Image.resize((135, 320))
Peter_Image = ImageTk.PhotoImage(Peter_Image)
Phillip_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Phillip.png')
Phillip_Image = Phillip_Image.resize((135, 320))
Phillip_Image = ImageTk.PhotoImage(Phillip_Image)
Richard_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Richard.png')
Richard_Image = Richard_Image.resize((135, 320))
Richard_Image = ImageTk.PhotoImage(Richard_Image)
Robert_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Robert.png')
Robert_Image = Robert_Image.resize((135, 320))
Robert_Image = ImageTk.PhotoImage(Robert_Image)
Sam_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Sam.png')
Sam_Image = Sam_Image.resize((135, 320))
Sam_Image = ImageTk.PhotoImage(Sam_Image)
Susan_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Susan.png')
Susan_Image = Susan_Image.resize((135, 320))
Susan_Image = ImageTk.PhotoImage(Susan_Image)
Tom_Image = Image.open(r'C:\Users\WebsterJacobM\Desktop\Guess Who\Character Images\Tom.png')
Tom_Image = Tom_Image.resize((135, 320))
Tom_Image = ImageTk.PhotoImage(Tom_Image)

mainframe = ttk.Frame(window)
mainframe.grid(column=0, row=0, padx=20, pady=20)
Alex_Label = ttk.Label(mainframe, image=Alex_Image).pack()
Alfred_Label = ttk.Label(mainframe, image=Alfred_Image).pack()
window.mainloop()